# Generated by Django 3.1 on 2021-08-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanadDugsiyeedka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taariikhdaBillowgaHijri', models.CharField(max_length=10)),
                ('taariikhdaDhamaadkaHijri', models.CharField(max_length=10)),
                ('taariikhdaBillowgaMiladi', models.CharField(max_length=10)),
                ('taariikhdaDhamaadkaMIladi', models.CharField(max_length=10)),
            ],
        ),
    ]
