# Generated by Django 3.1 on 2021-08-30 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darulxadith_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mustawaha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magacaMustawaha', models.CharField(max_length=100)),
                ('maadoyinka', models.CharField(max_length=1000)),
                ('sanadDugsiyeedka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darulxadith_system.sanaddugsiyeedka')),
            ],
        ),
    ]
