# Generated by Django 3.1 on 2021-08-30 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darulxadith_system', '0002_mustawaha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ardada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magacaArdayga', models.CharField(max_length=255)),
                ('jinsiga', models.CharField(default='lab', max_length=10)),
                ('sawirkaArdayga', models.ImageField(blank=True, null=True, upload_to='images/sawirada_ardada/')),
                ('meeshaDhalashada', models.CharField(blank=True, max_length=100, null=True)),
                ('waqtigaDhalashada', models.CharField(blank=True, max_length=100, null=True)),
                ('numberkaArdayga', models.IntegerField()),
                ('magacaMasuulka', models.CharField(blank=True, max_length=100, null=True)),
                ('numberkaMasuulka', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Xalqada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magacaXalqada', models.CharField(max_length=255)),
                ('mustawaha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darulxadith_system.mustawaha')),
            ],
        ),
        migrations.CreateModel(
            name='Natiijada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imtixanka', models.CharField(max_length=30)),
                ('maadada', models.CharField(max_length=50)),
                ('buundada', models.IntegerField()),
                ('tarikhdaLagalay', models.CharField(blank=True, max_length=10, null=True)),
                ('magacaArdayga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darulxadith_system.ardada')),
                ('xalqada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darulxadith_system.xalqada')),
            ],
        ),
        migrations.CreateModel(
            name='Imtixaanada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magacaImtixanka', models.CharField(max_length=255)),
                ('tarikhdaLagalay', models.DateField()),
                ('sanadDugsiyeedka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darulxadith_system.sanaddugsiyeedka')),
            ],
        ),
        migrations.AddField(
            model_name='ardada',
            name='mustawahaArdayga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darulxadith_system.xalqada'),
        ),
    ]
