# Generated by Django 3.1 on 2021-08-30 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darulxadith_system', '0003_auto_20210830_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='natiijada',
            name='sanadka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='darulxadith_system.sanaddugsiyeedka'),
            preserve_default=False,
        ),
    ]
