# Generated by Django 3.1 on 2021-09-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darulxadith_system', '0004_natiijada_sanadka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natiijada',
            name='maadada',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
