# Generated by Django 3.1 on 2021-09-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darulxadith_system', '0005_auto_20210901_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natiijada',
            name='maadada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
