# Generated by Django 3.1 on 2021-09-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darulxadith_system', '0006_auto_20210901_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natiijada',
            name='buundada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
