# Generated by Django 3.1 on 2021-09-05 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darulxadith_system', '0007_auto_20210901_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xaadiriska',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabti1', models.IntegerField(default=1)),
                ('sabti2', models.IntegerField(default=1)),
                ('sabti3', models.IntegerField(default=1)),
                ('sabti4', models.IntegerField(default=1)),
                ('axad1', models.IntegerField(default=1)),
                ('axad2', models.IntegerField(default=1)),
                ('axad3', models.IntegerField(default=1)),
                ('axad4', models.IntegerField(default=1)),
                ('isniin1', models.IntegerField(default=1)),
                ('isniin2', models.IntegerField(default=1)),
                ('isniin3', models.IntegerField(default=1)),
                ('isniin4', models.IntegerField(default=1)),
                ('talaado1', models.IntegerField(default=1)),
                ('talaado2', models.IntegerField(default=1)),
                ('talaado3', models.IntegerField(default=1)),
                ('talaado4', models.IntegerField(default=1)),
                ('arbaco1', models.IntegerField(default=1)),
                ('arbaco2', models.IntegerField(default=1)),
                ('arbaco3', models.IntegerField(default=1)),
                ('arbaco4', models.IntegerField(default=1)),
                ('waqtiga', models.DateField()),
                ('waqtigaLaQadayo', models.DateField()),
                ('magacaArdayga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darulxadith_system.ardada')),
                ('xalqada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darulxadith_system.xalqada')),
            ],
        ),
    ]
