# Generated by Django 3.2.7 on 2021-09-19 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darulxadith_system', '0008_xaadiriska'),
    ]

    operations = [
        migrations.AddField(
            model_name='ardada',
            name='sanadDugsiyedka',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='darulxadith_system.sanaddugsiyeedka'),
        ),
        migrations.AddField(
            model_name='ardada',
            name='tarikhdaDiwangalinta',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
