# Generated by Django 3.2.7 on 2021-09-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darulxadith_system', '0009_auto_20210919_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natiijada',
            name='buundada',
            field=models.IntegerField(default=0),
        ),
    ]
