# Generated by Django 3.2.7 on 2021-10-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darulxadith_system', '0012_mulaaxadaat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ardada',
            name='numberkaArdayga',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ardada',
            name='numberkaMasuulka',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
