# Generated by Django 3.2.7 on 2021-10-07 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('darulxadith_system', '0013_auto_20211002_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mulaaxadaat',
            name='waqtiga',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
